ALTER TABLE user ADD COLUMN role VARCHAR(20) DEFAULT 'client';
ALTER TABLE processes ADD COLUMN status VARCHAR(50) DEFAULT 'Pending';
ALTER TABLE processes ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;